name: AmawtaLab
favicon: null
layout_spectrum: 0.25211
typography_spectrum: 0.4993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc2a1c'
    - '#6a6a6a'
    - '#000000'
    - '#bdbdbd'
  brandStrength: 0.3330741
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.393855
purpose: []
