name: AmawtaLab
favicon: null
layout_spectrum: 0.7136592
typography_spectrum: 0.4035088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc2a1c'
    - '#6a6a6a'
    - '#000000'
    - '#bdbdbd'
  brandStrength: 0.3330741
  lightness: 0.06215725
  saturation: 0.233166
  rhythmicContrast: 0.393855
purpose: []
